---
ID: "705abaae-c6a7-41ae-a5ba-883ced9d5c4e"
Parent: "2325b50c-9de9-47e5-a432-1f983e9fa3f8"
Template: "a87a00b1-e6db-45ab-8b54-636fec3b5523"
Path: /sitecore/Forms/Habitat Sites/Habitat Home/Content Finder Form/Page 2/Columns Wrapper/Field Wrapper/Question2/Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171121T163612Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
- Language: "ja-JP"
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: 設定
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180321T104943Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
