---
ID: "c74ac643-53c8-4f1e-9508-840cdc72aaca"
Parent: "0de95ae4-41ab-4d01-9eb0-67441b7c2450"
Template: "a87a00b1-e6db-45ab-8b54-636fec3b5523"
Path: /sitecore/content/Applications
DB: core
BranchID: "30235f43-6242-4107-87ab-5267e34edf0c"
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: Software/16x16/application.png
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: tree list
  Value: |
    {1F0770EA-8B77-4110-91AA-CC00DEE102DD}
    {73C2385C-9A34-4125-9419-F64376B34A62}
- ID: "56776edf-261c-4abc-9fe7-70c618795239"
  Hint: __Help link
  Value: 
- ID: "9c6106ea-7a5a-48e2-8cad-f0f693b1e2d4"
  Hint: __Read Only
  Type: checkbox
  Value: 0
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 10
- ID: "dec8d2d5-e3cf-48b6-a653-8e69e2716641"
  Hint: __Security
  Value: 
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: 
Languages:
- Language: en
  Fields:
  - ID: "9541e67d-ce8c-4225-803d-33f7f29f09ef"
    Hint: __Short description
    Value: Client applications.
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Applications
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "1ea6ce3a-49b9-4427-9bb2-320960231896"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20080124T111323
