---
ID: "34a2c763-cc57-4621-8497-6c89b4b51544"
Parent: "1c1b88ad-425a-4349-9a51-27d1fc4b8357"
Template: "1c1b88ad-425a-4349-9a51-27d1fc4b8357"
Path: /sitecore/templates/Project/Habitat SXA Sites/Global/Pages/Article Page/__Standard Values
DB: master
SharedFields:
- ID: "1fbc6a49-6281-48ee-87e9-a3970b145adb"
  Hint: NavigationFilter
  Type: Checklist
  Value: "{D063E9D1-C7B5-4B1E-B31E-69886C9C59F5}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171108T165829Z
