---
ID: "3e600e5a-3d08-4c25-874c-138cd1dcc80b"
Parent: "9b479b57-aae9-4601-abb4-e48adc72b368"
Template: "9b479b57-aae9-4601-abb4-e48adc72b368"
Path: /sitecore/templates/Feature/Habitat Home/News/NewsSettings/__Standard Values
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: /~/icon/network/32x32/news_edit.png
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "1c3cd945-0297-4609-9d65-ee26b74d4a4e"
      Hint: NewsOverviewDefaultNumberOfItems
      Value: 10
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190502T052030Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
