---
ID: "fe114d87-47ca-4324-8713-b5a68e651421"
Parent: "0d00a090-b7ca-4296-9b6d-b0fcc0c34bb4"
Template: "0d00a090-b7ca-4296-9b6d-b0fcc0c34bb4"
Path: /sitecore/templates/Feature/Habitat Home/Habitat Home XA Extensions/Page Content/Rendering Parameters/Hero/__Standard Values
DB: master
Created: 20190425T163459Z
SharedFields:
- ID: "3094d236-5985-4c4f-ae6a-e30740885532"
  Hint: Caching
  Value: 0|0|0|0|0|0|0|0
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120629T104300
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ad2beb58-fbd7-49ef-bd98-3f2f72752002"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\unicorn
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190425T163459Z
