version: '2.4'

networks:
  demo:

services:

  sql:
    image: ${REGISTRY}habitathome-xp-sqldev:9.2.0-windowsservercore-${WINDOWSSERVERCORE_CHANNEL}
    mem_limit: 4G
    cpus: 0
    networks:
      demo:
    volumes:
      - .\data\sql:C:\Data
    ports:
      - "44010:1433"

  solr:
    image: ${REGISTRY}sitecore-xp-sxa-solr:9.2.0-nanoserver-${NANOSERVER_CHANNEL}
    mem_limit: 2G
    cpus: 0
    networks:
      demo:
    volumes:
      - .\data\solr:C:\Data
    ports:
      - "44011:8983"

  xconnect:
    image: ${REGISTRY}habitathome-xp-xconnect:9.2.0-windowsservercore-${WINDOWSSERVERCORE_CHANNEL}
    mem_limit: 1G
    networks:
      demo:
    entrypoint: cmd /c "COPY C:\license\license.xml C:\inetpub\wwwroot\App_Data\license.xml & powershell Watch-Directory.ps1 C:\src C:\inetpub\wwwroot -ExcludeFiles @('ConnectionStrings.config')"
    volumes:
      - c:\license:c:\license
      - .\data\xconnect:C:\inetpub\wwwroot\App_Data\logs
      - .\publish\xconnect:C:\src
    links:
      - sql
      - solr

  xconnect-automationengine:
    image: ${REGISTRY}sitecore-xp-xconnect-automationengine:9.2.0-windowsservercore-${WINDOWSSERVERCORE_CHANNEL}
    mem_limit: 1G
    networks:
      demo:
    volumes:
      - c:\license:c:\license
      - .\data\xconnect-automationengine:C:\inetpub\wwwroot\App_Data\logs
    links:
      - sql
      - xconnect

  xconnect-indexworker:
    image: ${REGISTRY}habitathome-xp-xconnect-indexworker:9.2.0-windowsservercore-${WINDOWSSERVERCORE_CHANNEL}
    mem_limit: 1G
    networks:
      demo:
    entrypoint: cmd /c "COPY C:\license\license.xml C:\inetpub\wwwroot\App_Data\license.xml & powershell Watch-Directory.ps1 C:\src C:\inetpub\wwwroot -ExcludeFiles @('ConnectionStrings.config')"
    volumes:
      - c:\license:c:\license
      - .\data\xconnect-indexworker:C:\inetpub\wwwroot\App_Data\logs
      - .\Publish\xConnect\App_data\jobs\continuous\IndexWorker:c:\src
    links:
      - sql
      - solr

#   cd:
#    image: ${REGISTRY}sitecore-xp-sxa-1.9.0-cd:9.2.0-windowsservercore-${WINDOWSSERVERCORE_CHANNEL}
#    networks:
#      demo:
#    volumes:
#      - .\data\cd:C:\inetpub\sc\App_Data\logs
#    ports:
#      - "44002:80"
#    links:
#      - sql
#      - solr
#      - xconnect

  cm:
    image: ${REGISTRY}habitathome-xp-standalone:9.2.0-windowsservercore-${WINDOWSSERVERCORE_CHANNEL}
    mem_limit: 4G
    cpus: 0
    networks:
      demo:
        aliases:
          - local-cms.demo.com
    entrypoint: cmd /c "start /B powershell Watch-Directory.ps1 C:\src C:\inetpub\wwwroot -ExcludeFiles @('ConnectionStrings.config') & powershell C:/scripts/CopyConfigs.ps1 & C:\\remote_debugger\\x64\\msvsmon.exe /noauth /anyuser /silent /nostatus /noclrwarn /nosecuritywarn /nofirewallwarn /nowowwarn /timeout:2147483646"
    volumes:
      - .\scripts\Docker:C:\scripts
      - c:\license:c:\license
      - .\publish\web:C:\src
      - .\items:c:\unicorn
      - .\data\cm:C:\inetpub\wwwroot\App_Data\logs
      - .\data\creativeexchange:C:\inetpub\wwwroot\App_Data\packages\CreativeExchange\FileStorage
      - ${REMOTEDEBUGGER_PATH}:C:\remote_debugger:ro
    ports:
      - "44001:80"
    links:
      - sql
      - solr
      - xconnect
