---
ID: "3e54a390-bffd-40e6-9af7-e951a806e691"
Parent: "10083ca0-5093-4d67-99db-2579abb421d3"
Template: "69dd5f28-429f-46b6-b55c-9da3500a7369"
Path: /sitecore/content/Habitat Sites/Habitat Home/home/services
DB: master
SharedFields:
- ID: "1fbc6a49-6281-48ee-87e9-a3970b145adb"
  Hint: NavigationFilter
  Type: Checklist
  Value: "{D063E9D1-C7B5-4B1E-B31E-69886C9C59F5}"
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: "{C6EBE5E6-BCE3-4BAB-A5F9-16382F8369FE}"
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 1050
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:p="p" xmlns:s="s"
      p:p="1">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
        <r
          uid="{D13C9ED0-2890-492A-A7EC-F54D1736ECB7}"
          p:before="*"
          s:ds="{CD5572D3-B6FC-4A9A-89B6-36E4EC0E1B0E}"
          s:id="{51C13F03-8364-4F61-B860-2EC6CA7439B3}"
          s:par="GridParameters=%7B113BEF7C-97E6-46CA-8CF3-916F7FAA8DE2%7D&amp;FieldNames=%7B6C6DCD16-6835-4C2B-BC30-B19AF38AAB21%7D&amp;Styles&amp;Reset Caching Options&amp;RenderingIdentifier&amp;DynamicPlaceholderId=6"
          s:ph="/main/sxa-content-container/container-1/container-3/column-2-4" />
        <r
          uid="{5266A527-8065-49C4-92EC-536B3857D1A7}"
          p:after="r[@uid='{D13C9ED0-2890-492A-A7EC-F54D1736ECB7}']"
          s:ds="{3E8652BF-C174-4CEF-B1EF-1FD7408579FC}"
          s:id="{51C13F03-8364-4F61-B860-2EC6CA7439B3}"
          s:par="GridParameters=%7B113BEF7C-97E6-46CA-8CF3-916F7FAA8DE2%7D&amp;FieldNames=%7B6C6DCD16-6835-4C2B-BC30-B19AF38AAB21%7D&amp;Styles&amp;Reset Caching Options&amp;RenderingIdentifier&amp;DynamicPlaceholderId=5"
          s:ph="/main/sxa-content-container/container-1/container-3/column-1-4" />
        <r
          uid="{B319B291-B2E6-47A3-982D-6228B18FBB5B}"
          p:after="r[@uid='{5266A527-8065-49C4-92EC-536B3857D1A7}']"
          s:id="{C25766C8-9AFD-4D28-87FE-147774F6806D}"
          s:par="SplitterSize=2&amp;EnabledPlaceholders=1,2&amp;Styles1&amp;Styles2&amp;Styles3&amp;Styles4&amp;Styles5&amp;Styles6&amp;Styles7&amp;Styles8&amp;ColumnWidth1={FB140AEF-DE33-4088-9F1D-406C6BA32A8E}&amp;ColumnWidth2={FB140AEF-DE33-4088-9F1D-406C6BA32A8E}&amp;ColumnWidth3&amp;ColumnWidth4&amp;ColumnWidth5&amp;ColumnWidth6&amp;ColumnWidth7&amp;ColumnWidth8&amp;Reset Caching Options&amp;DynamicPlaceholderId=4"
          s:ph="/main/sxa-content-container/container-1/container-3" />
        <r
          uid="{87DB5200-7806-4555-9785-5D3E47D522D7}"
          p:after="r[@uid='{B319B291-B2E6-47A3-982D-6228B18FBB5B}']"
          s:ds="local:/Data/Hero - Services"
          s:id="{6BCF8D8E-0A28-4844-BFB4-96C852BAD2DC}"
          s:par="GridParameters={113BEF7C-97E6-46CA-8CF3-916F7FAA8DE2}&amp;FieldNames&amp;Styles&amp;Reset Caching Options&amp;RenderingIdentifier&amp;DynamicPlaceholderId=1"
          s:ph="/main/sxa-content-container/container-1" />
        <r
          uid="{3E87A375-CEBC-45B6-82FE-54FDCDB20363}"
          p:after="r[@uid='{87DB5200-7806-4555-9785-5D3E47D522D7}']"
          s:ds="local:/Data/Promo - Gift Card"
          s:id="{51C13F03-8364-4F61-B860-2EC6CA7439B3}"
          s:par="GridParameters=%7B113BEF7C-97E6-46CA-8CF3-916F7FAA8DE2%7D&amp;FieldNames=%7B184DC7A4-FDBB-446F-94BE-30B44B12C2AD%7D&amp;Styles&amp;Reset Caching Options&amp;RenderingIdentifier&amp;DynamicPlaceholderId=7"
          s:ph="/main/sxa-content-container/container-1" />
        <r
          uid="{C68253C2-8B71-4A9E-B39A-F82576C73DFF}"
          p:after="r[@uid='{3E87A375-CEBC-45B6-82FE-54FDCDB20363}']"
          s:ds="local:/Data/Promo - Home Installation"
          s:id="{51C13F03-8364-4F61-B860-2EC6CA7439B3}"
          s:par="GridParameters=%7B113BEF7C-97E6-46CA-8CF3-916F7FAA8DE2%7D&amp;FieldNames=%7BF8C8F184-053D-4947-840B-A96495DB434C%7D&amp;Styles&amp;Reset Caching Options&amp;RenderingIdentifier&amp;DynamicPlaceholderId=8"
          s:ph="/main/sxa-content-container/container-1" />
        <r
          uid="{5AB6F3A7-2411-4E08-A1B9-47C8EFD7BBB8}"
          p:after="r[@uid='{C68253C2-8B71-4A9E-B39A-F82576C73DFF}']"
          s:ds="local:/Data/Promo - Ultimate Smart Home Checklist"
          s:id="{51C13F03-8364-4F61-B860-2EC6CA7439B3}"
          s:par="GridParameters=%7B113BEF7C-97E6-46CA-8CF3-916F7FAA8DE2%7D&amp;FieldNames=%7B184DC7A4-FDBB-446F-94BE-30B44B12C2AD%7D&amp;Styles&amp;Reset Caching Options&amp;RenderingIdentifier&amp;DynamicPlaceholderId=2"
          s:ph="/main/sxa-content-container/container-1" />
        <r
          uid="{FF3EAFD9-699B-49F5-833B-B9BE2FEFBD55}"
          p:after="*[1=2]"
          s:id="{896A2C68-1362-4E88-8BA0-1805AE6D4837}"
          s:par="GridParameters={F2FCE948-4F77-44AF-A188-B2030061F793}&amp;BackgroundImage&amp;Styles={45645D8F-56A4-460A-B5FB-51709FEFCE52}|{3D258225-9410-4FAF-A516-43490258337D}&amp;Reset Caching Options&amp;RenderingIdentifier&amp;DynamicPlaceholderId=3"
          s:ph="/main/sxa-content-container/container-1" />
      </d>
    </r>
Languages:
- Language: en
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Services
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180323T185620Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{E93E190F-3398-489D-B3A3-A3B0D9BB33C5}"
    - ID: "4e0720e9-9d50-4ddc-87cf-ecd65e8e94c8"
      Hint: NavigationTitle
      Value: Services
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "74687d7c-2ef8-47ef-a779-9a8040bb2d1a"
      Hint: Navigation Secondary Promotions
      Type: Treelist
      Value: |
        {39F4D78E-C5F1-4092-BC8C-CE270CBE7CA0}
        {7993B27B-B31E-4E84-8566-BCC291B3B418}
        {DDF8FE4E-B5ED-4975-8FC6-DDF68C479F6A}
    - ID: "c78d6b36-329e-4dc9-873a-39f4b0ea9a28"
      Hint: Navigation Promotions
      Type: Treelist
      Value: |
        {292595C9-5D69-4C82-B67E-8132352E9B5F}
        {281076EC-4D19-4EF9-97B8-DFBB77B319FB}
        {F753DBAC-A0CB-4FFE-8953-5C1124D32479}
    - ID: "e2a634fd-5177-46de-b629-5393caed77d7"
      Hint: Title
      Value: Services
- Language: "fr-CA"
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Services
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180807T045355Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{E93E190F-3398-489D-B3A3-A3B0D9BB33C5}"
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "74687d7c-2ef8-47ef-a779-9a8040bb2d1a"
      Hint: Navigation Secondary Promotions
      Type: Treelist
      Value: |
        {39F4D78E-C5F1-4092-BC8C-CE270CBE7CA0}
        {DDF8FE4E-B5ED-4975-8FC6-DDF68C479F6A}
        {7993B27B-B31E-4E84-8566-BCC291B3B418}
    - ID: "c78d6b36-329e-4dc9-873a-39f4b0ea9a28"
      Hint: Navigation Promotions
      Type: Treelist
      Value: |
        {281076EC-4D19-4EF9-97B8-DFBB77B319FB}
        {F753DBAC-A0CB-4FFE-8953-5C1124D32479}
        {292595C9-5D69-4C82-B67E-8132352E9B5F}
    - ID: "e2a634fd-5177-46de-b629-5393caed77d7"
      Hint: Title
      Value: Services
- Language: "ja-JP"
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: サービス
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180817T180340Z
    - ID: "4e0720e9-9d50-4ddc-87cf-ecd65e8e94c8"
      Hint: NavigationTitle
      Value: サービス
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        extranet\Anonymous
    - ID: "e2a634fd-5177-46de-b629-5393caed77d7"
      Hint: Title
      Value: サービス
