---
ID: "766adcf0-569e-43cb-8ee7-3bbcf18b1c65"
Parent: "5a5deef3-c463-43dd-9b44-30c549a7c949"
Template: "5a5deef3-c463-43dd-9b44-30c549a7c949"
Path: /sitecore/templates/Project/Habitat SXA Sites/Global/Page Design Folder/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: |
    {5A5DEEF3-C463-43DD-9B44-30C549A7C949}
    {26336120-B85F-4BF2-A988-290C7B3328FC}
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171027T151102Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\virtualssuser
