---
ID: "78d3dcc1-33c9-4028-a100-21573eb92a28"
Parent: "f7a56f00-e12e-49ce-af4f-a92b2529618d"
Template: "f7a56f00-e12e-49ce-af4f-a92b2529618d"
Path: /sitecore/templates/Foundation/Habitat Home/Workflow/Submission Notification/__Standard Values
DB: master
SharedFields:
- ID: "3cb83e5d-8b67-4ba5-9bc6-e9f122ad95cb"
  Hint: Mail Server
  Value: localhost
- ID: "a291a22b-99e2-46bb-a27b-8ec744275396"
  Hint: Type
  Value: Sitecore.HabitatHome.Foundation.Workflow.Actions.SubmissionNotification, Sitecore.HabitatHome.Foundation.Workflow
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180530T150354Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
