---
ID: "06830b85-c52c-4618-bd6e-c990c660e8b9"
Parent: "8b06db5e-9993-4ee0-8706-6959dd7b6c45"
Template: "be2a1204-f7ba-4be3-933d-190c97496700"
Path: /sitecore/content/Demo SXA Sites/LighthouseFinancial/Settings
DB: master
BranchID: "b90549b5-c997-4d6b-b102-c9ab82528974"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: |
    {11F57D7B-CBB2-4647-B98C-71457564BA4F}
    {0D792404-79AA-483D-BB0C-50785F2E295B}
    {F86FE270-00A4-492F-BFAF-5BF27E40CE13}
    {E1CF805E-7F49-4EC9-A25A-182DC798CB5F}
    {DC66D5DA-3216-48E6-AE78-BAC8445B6A46}
    {70461699-48E4-45FA-B74B-0CCE849FCA6A}
    {20EF5E69-B366-4E9E-960B-E451B24DBD46}
    {5C76AD53-96CD-4B96-9690-DD9AF2650171}
    {44936C95-BCA9-4FB3-9D98-2066A5FBBB4D}
    {5A6BF1D1-836B-425A-A6E6-32CEAA8FF3A5}
    {B14BAB5B-8965-466B-886B-1F93175BCAB3}
    {041C1F9F-99A4-4EE6-8308-985499F91032}
- ID: "af332c24-fe17-41e7-8caf-8e64c588fe72"
  Hint: EditingTheme
  Value: "{F507742D-BE41-4A0F-B06A-D489AC14A372}"
- ID: "beeede03-ab13-4558-96f9-c3e8957b46f8"
  Hint: Themes
  Type: Treelist
  Value: "{42F73047-90E1-4916-9C3F-B8632616178F}"
- ID: "e81e1f9e-8b87-495b-9cb7-84a2a23133be"
  Hint: MediaLibrary
  Value: "{04EAF0F7-6180-414D-B598-34138B9AE719}"
- ID: "e8881464-38af-4655-be4a-ee10586578a2"
  Hint: Templates
  Value: "{93F3857B-50B9-4A2D-ADE8-95F3B2F53005}"
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{3E739E69-859C-4694-8D14-2BA6CA779CC6}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200511T215905Z
