---
ID: "17c80de0-d822-4b40-afb1-b7e87739dbc1"
Parent: "69dd5f28-429f-46b6-b55c-9da3500a7369"
Template: "69dd5f28-429f-46b6-b55c-9da3500a7369"
Path: /sitecore/templates/Project/Habitat SXA Sites/Global/Pages/L1 Content Page/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: |
    {E3B950BB-1B55-4CDD-819F-031B3BE1A66C}
    {C14B6289-8AC2-439C-9E5B-40DE9F820C3F}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171117T175503Z
