---
ID: "8301a7c7-5e05-4232-bc12-e799ea710c2c"
Parent: "98e4bdc6-9b43-4eb2-baa3-d4303c35852e"
Template: "98e4bdc6-9b43-4eb2-baa3-d4303c35852e"
Path: /sitecore/templates/Foundation/Habitat Home/Dictionary/DictionaryFolder/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: |
    {EC4DD3F2-590D-404B-9189-2A12679749CC}
    {98E4BDC6-9B43-4EB2-BAA3-D4303C35852E}
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160405T224848Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
