---
ID: "af1a71b0-ecf0-4e1b-8515-2d3b4ca8ec3e"
Parent: "fe489c3e-29d8-47f7-86da-c441d3f6e0e5"
Template: "fe489c3e-29d8-47f7-86da-c441d3f6e0e5"
Path: /sitecore/templates/Project/Habitat Sites/Habitat Home/Pages/Account Management/Address Book/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: |
    {F6C621CE-6176-4F83-AEE3-84AF17EEAA94}
    {C14B6289-8AC2-439C-9E5B-40DE9F820C3F}
    {C7B45FE1-189F-47CB-A9E4-6DE27E67D00F}
    {2C7F849B-62F5-40E5-A209-1F0B6630A7DE}
    {F570E8B5-163F-4DE0-A28E-C27EB798AC4E}
    {CED1B68C-BC10-4A08-96A5-7DE4F4162E71}
    {5C5DEC1C-7ABD-48E3-921E-D7A70FE9FDA7}
    {26D64CFB-58A3-4B0C-92F2-D1351152302A}
    {A721F186-33A5-4641-84FD-14499C2C03D8}
    {6D8AEF90-D30E-4942-A1BB-32CD4864CDC9}
    {299683FC-1A7A-4A56-B512-977913C097DF}
    {FE489C3E-29D8-47F7-86DA-C441D3F6E0E5}
    {FED62AF9-1AC1-4516-81EF-2C0AF6464184}
    {E4B94ADC-6CE8-45D7-A0FD-C38147E63AC6}
    {87A8FC00-7F77-452F-8BD9-73EBEF05610B}
    {09996B1C-4641-4425-A940-A511966B0F93}
    {CD0B1C23-FFD4-4336-8D3F-EAEEA1911EB2}
    {6B1871AF-B8C4-4C39-81D9-E747764E62BF}
    {19855ED8-05C2-4595-B240-743831C3A2C7}
    {A8359172-32A7-47EE-9C1A-35CC46148CE6}
- ID: "d4952280-2d7d-4bf4-a99a-ea36dad0f0a7"
  Hint: Body Css Class
  Value: "address-book-page"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170811T075028Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
