---
ID: "8dbd70db-b85f-4bb7-85e8-1d79e01bb49f"
Parent: "cb5e16df-b01c-44a0-a4d6-c99235acf860"
Template: "cb5e16df-b01c-44a0-a4d6-c99235acf860"
Path: /sitecore/templates/Project/Habitat SXA Sites/Global/Pages/Account Page/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171214T153822Z
