---
ID: "0c93c1a6-165d-4e91-a0dc-a3ee4da83769"
Parent: "9dbd5091-a94a-4d49-9e47-06b8b4fa3c2c"
Template: "9dbd5091-a94a-4d49-9e47-06b8b4fa3c2c"
Path: /sitecore/templates/Feature/Habitat Home/Components/Base Content/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181206T162422Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "f4629649-b213-4e81-8f4d-59b8de35e6f2"
      Hint: Title
      Value: $name
