---
ID: "6cd04e2f-dbd2-4f9b-8093-dc724918129e"
Parent: "aca5f454-72e4-47bc-93a8-829621eeefe4"
Template: "a87a00b1-e6db-45ab-8b54-636fec3b5523"
Path: /sitecore/Forms/Habitat SXA Sites/Habitat Home/Weekly Fitness Report Signup/Page/Section/RunningTypeSection/Checkbox List/Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181206T044114Z
- Language: "fr-CA"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190426T201556Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        extranet\Anonymous
