---
ID: "00beee13-9fcb-4ee4-bdb9-54e6a8a6f61e"
Parent: "2d77e72e-4cee-47fa-97c1-d29c508a4173"
Template: "2d77e72e-4cee-47fa-97c1-d29c508a4173"
Path: /sitecore/templates/Feature/Habitat Home/Components/Carousel/CarouselFolder/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: |
    {55DEEEDA-D3EE-47C6-AD8D-1B61E5E94BAA}
    {2D77E72E-4CEE-47FA-97C1-D29C508A4173}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190121T194814Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
