---
ID: "e669c22f-596e-4a96-b978-474b5f54d493"
Parent: "ab2f413c-4854-48eb-b7eb-6fd2e8142b19"
Template: "7cc96707-325d-4024-9f58-b10ce1f950d1"
Path: /sitecore/system/Marketing Control Panel/Taxonomies/Campaign group/Commerce Automation
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180628T171634Z
- Language: "ja-JP"
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: "Commerce ????????"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190125T061142Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
