---
ID: "69747635-c2b0-4a48-a2c1-4706e341ce1a"
Parent: "87159879-b717-474f-b4e5-683fb09f3ded"
Template: "87159879-b717-474f-b4e5-683fb09f3ded"
Path: /sitecore/templates/Feature/Habitat Home/Components/Metadata/MetadataBase/__Standard Values
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: "/~/icon/business/32x32/pie-chart_view.png"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190425T121336Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "60a36bf8-cb0e-40f6-8b5a-834105136988"
      Hint: MetadataTitle
      Value: $name
