---
ID: "97a08206-9372-4d57-a5c4-d04bfa74c222"
Parent: "e255d331-aea1-4f66-a5e7-4ab2e26408e0"
Template: "e255d331-aea1-4f66-a5e7-4ab2e26408e0"
Path: /sitecore/templates/Project/Demo Shared SXA Sites/Content Hub Entity Types/Content Hub Article/__Standard Values
DB: master
SharedFields:
- ID: "4d71857f-c77d-44fa-8899-c671a0458d7f"
  Hint: Publish Date
  Value: $now
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: "{C6EBE5E6-BCE3-4BAB-A5F9-16382F8369FE}"
- ID: "c9283d9e-7c29-4419-9c28-5a5c8ff53e84"
  Hint: __Bucketable
  Type: Checkbox
  Value: 0
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{BCFC7537-EFF4-434C-96F5-BF4F55FD175B}">
        <r
          ds=""
          id="{0FA50A16-13DF-4722-9357-C7D157638ACA}"
          par="Reset Caching Options&amp;GridParameters&amp;FieldNames&amp;Styles&amp;RenderingIdentifier&amp;DynamicPlaceholderId=1"
          ph="/main/sxa-article-content/container-1/column-2-2/container-4"
          uid="{C489AFA7-7AF8-476C-9A89-19BAFDDCCD27}" />
      </d>
      <d
        id="{0B4A31C9-712D-4578-A396-2DDC0F34B63A}"
        l="{72C595AD-68BB-44BC-B5CD-2A857039515F}" />
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190614T161122Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: 
