---
ID: "c8d05203-47c3-48fb-bf7b-37396c1062e5"
Parent: "308c0f53-2923-4652-aac6-03c2b477c325"
Template: "962b53c4-f93b-4df9-9821-415c867b8903"
Path: /sitecore/media library/Themes/Habitat SXA Sites/Sitecore Demo/gulp/tasks/cssOptimization
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: "-/media/B6C0D49CD9974FE787563A366BCB8F6F.ashx?h=16&thn=1&w=16"
- ID: "40e50ed9-ba07-4702-992e-a912738d32dc"
  Hint: Blob
  BlobID: "0e4c5514-e2e9-4dbf-85f7-386c65bb226c"
  Value: aW1wb3J0IGd1bHAgZnJvbSAnZ3VscCc7DQppbXBvcnQgY3NzTWluaWZpY2F0b3IgZnJvbSAnLi4vdXRpbC9jc3NNaW5pZmljYXRvcic7DQoNCmd1bHAudGFzaygnY3NzT3B0aW1pc2UnLCAoKSA9PiB7DQogICAgcmV0dXJuIGNzc01pbmlmaWNhdG9yKCkNCn0p
- ID: "6954b7c7-2487-423f-8600-436cb3b6dc0e"
  Hint: Size
  Value: 147
- ID: "6f47a0a5-9c94-4b48-abeb-42d38def6054"
  Hint: Mime Type
  Value: "application/x-javascript"
- ID: "c06867fe-9a43-4c7d-b739-48780492d06f"
  Hint: Extension
  Value: js
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190410T083131Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
