---
ID: "b352fed0-83f4-450e-bf99-fa02272a96ea"
Parent: "308c0f53-2923-4652-aac6-03c2b477c325"
Template: "962b53c4-f93b-4df9-9821-415c867b8903"
Path: /sitecore/media library/Themes/Habitat SXA Sites/Sitecore Demo/gulp/tasks/watchCss
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: "-/media/0EC44B6207604EF2ADC8B695A258B384.ashx?h=16&thn=1&w=16"
- ID: "40e50ed9-ba07-4702-992e-a912738d32dc"
  Hint: Blob
  BlobID: "97fda39b-afb1-4c1c-88b1-11931ba74027"
  Value: aW1wb3J0IGd1bHAgZnJvbSAnZ3VscCc7DQppbXBvcnQgc2FzcyBmcm9tICdndWxwLXNhc3MnOw0KaW1wb3J0IHdhdGNoIGZyb20gJ2d1bHAtd2F0Y2gnOw0KaW1wb3J0IGNvbG9ycyBmcm9tICdjb2xvcnMnDQovLw0KaW1wb3J0IGxvZ2luIGZyb20gJy4vbG9naW4nOw0KaW1wb3J0IGNvbmZpZyBmcm9tICcuLi9jb25maWcnOw0KDQppbXBvcnQgeyBmaWxlQWN0aW9uUmVzb2x2ZXIsIHF1ZXVlSW5zdGFuY2UgfSBmcm9tICcuLi91dGlsL2ZpbGVBY3Rpb25SZXNvbHZlcic7DQppbXBvcnQgY3NzTWluaWZpY2F0b3IgZnJvbSAnLi4vdXRpbC9jc3NNaW5pZmljYXRvcic7DQovLw0KDQpndWxwLnRhc2soJ3dhdGNoLWNzcycsIFsnbG9naW4nXSwgKCkgPT4gew0KICAgIHZhciBjb25mID0gY29uZmlnLmNzcywNCiAgICAgICAgaW5kZXJ2YWxJZDsNCiAgICBzZXRUaW1lb3V0KGZ1bmN0aW9uICgpIHsNCiAgICAgICAgY29uc29sZS5sb2coJ1dhdGNoaW5nIENTUyBmaWxlcyBzdGFydGVkLi4uJy5ncmVlbik7DQogICAgfSwgMCk7DQogICAgcmV0dXJuIHdhdGNoKGNvbmYucGF0aCwgZnVuY3Rpb24gKGZpbGUpIHsNCiAgICAgICAgaWYgKCFjb25mLmRpc2FibGVTb3VyY2VVcGxvYWRpbmcgfHwgZmlsZS5wYXRoLmluZGV4T2YoY29uZi5jc3NPcHRpbWlzZXJGaWxlTmFtZSkgPiAtMSkgew0KICAgICAgICAgICAgZmlsZUFjdGlvblJlc29sdmVyKGZpbGUpOw0KICAgICAgICB9IGVsc2Ugew0KICAgICAgICAgICAgY29uc29sZS5sb2coJ1VwbG9hZGluZyBwcmV2ZW50ZWQgYmVjYXVzZSB2YWx1ZSBkaXNhYmxlU291cmNlVXBsb2FkaW5nOnRydWUnLnllbGxvdyk7DQoNCiAgICAgICAgfQ0KICAgICAgICBpZiAoY29uZi5lbmFibGVNaW5pZmljYXRpb24gJiYgZmlsZS5wYXRoLmluZGV4T2YoY29uZi5jc3NPcHRpbWlzZXJGaWxlTmFtZSkgPT0gLTEgJiYgIWluZGVydmFsSWQpIHsNCiAgICAgICAgICAgIGluZGVydmFsSWQgPSBzZXRJbnRlcnZhbChmdW5jdGlvbiAoKSB7DQogICAgICAgICAgICAgICAgaWYgKHF1ZXVlSW5zdGFuY2UucXVldWVMZW5naHQoKSA9PSAwKSB7DQogICAgICAgICAgICAgICAgICAgIGluZGVydmFsSWQgPSBjbGVhckludGVydmFsKGluZGVydmFsSWQpOw0KICAgICAgICAgICAgICAgICAgICBjc3NNaW5pZmljYXRvcigpOw0KICAgICAgICAgICAgICAgIH0NCiAgICAgICAgICAgIH0sIDE1MDApDQogICAgICAgIH0NCiAgICB9KQ0KfSk7DQoNCmd1bHAudGFzaygnY3NzLXdhdGNoJywgWydsb2dpbiddLA0KICAgIGZ1bmN0aW9uICgpIHsNCiAgICAgICAgZ2xvYmFsLmlzV2F0Y2hpbmcgPSB0cnVlOw0KICAgICAgICBndWxwLnJ1bignd2F0Y2gtY3NzJykNCiAgICB9KQ==
- ID: "6954b7c7-2487-423f-8600-436cb3b6dc0e"
  Hint: Size
  Value: 1348
- ID: "6f47a0a5-9c94-4b48-abeb-42d38def6054"
  Hint: Mime Type
  Value: "application/x-javascript"
- ID: "c06867fe-9a43-4c7d-b739-48780492d06f"
  Hint: Extension
  Value: js
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170614T065211Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
