---
ID: "3729f1cb-f39e-43f3-8f81-433e439f1ccf"
Parent: "b367156b-18c2-4010-91ab-ac9fbdbb9237"
Template: "a87a00b1-e6db-45ab-8b54-636fec3b5523"
Path: /sitecore/Forms/Demo Shared SXA Sites/Habitat Home/Content And Product Finder Form/Page 1/Columns Wrapper/Field Wrapper/Question 1/Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190725T192718Z
