---
ID: "e666b854-d1c1-47e5-b534-1565d358c1f0"
Parent: "25368f73-e153-4bd9-9cdc-943e882045d8"
Template: "76da0a8d-fc7e-42b2-af1e-205b49e43f98"
Path: /sitecore/content/Habitat Sites/Habitat Home/Presentation/Available Renderings/Security
DB: master
SharedFields:
- ID: "715ae6c0-71c8-4744-ab4f-65362d20ad65"
  Hint: Renderings
  Type: TreelistEx
  Value: |
    {596DBC32-8F3B-4B67-9CAA-889B5F8DF538}
    {E7AF0BB2-969E-4B4F-86AC-62FC4F2FE2D6}
    {CC2EB160-8FA6-4894-B599-2CEE7FC76820}
    {BE49452B-89FA-4D51-8589-7EFA522B94FE}
    {809FDBFF-892F-40F5-BD5D-97A021C711C1}
    {E441A637-F081-4FB7-8780-04DFE9419FEE}
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{576E5F9A-C304-4437-9478-F307575CCA28}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171027T191743Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\virtualssuser
- Language: "fr-CA"
  Fields:
  - ID: "41c6cc0e-389f-4d51-9990-fe35417b6666"
    Hint: __Preview
    Value: 
  - ID: "577f1689-7de4-4ad2-a15f-7fdc1759285f"
    Hint: __Long description
    Value: 
  - ID: "9541e67d-ce8c-4225-803d-33f7f29f09ef"
    Hint: __Short description
    Value: 
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: 
  Versions:
  - Version: 1
    Fields:
    - ID: "04bf00db-f5fb-41f7-8ab7-22408372a981"
      Hint: __Final Renderings
      Type: Layout
      Value: 
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171027T191743Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: 
    - ID: "4c346442-e859-4efd-89b2-44aedf467d21"
      Hint: __Valid to
      Value: 
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\virtualssuser
    - ID: "700f4aad-ad3b-4058-8673-a0cee765a1f7"
      Hint: __Content Test
      Value: 
    - ID: "a14f1b0c-4384-49ec-8790-28a440f3670c"
      Hint: __Semantics
      Type: Multilist with Search
      Value: 
    - ID: "b8f42732-9cb8-478d-ae95-07e25345fb0f"
      Hint: __Hide version
      Type: checkbox
      Value: 0
    - ID: "c8f93afe-bfd4-4e8f-9c61-152559854661"
      Hint: __Valid from
      Value: 
