---
ID: "e6292b09-a235-4c35-89b3-8c036e43f7b3"
Parent: "c2786e73-44c7-43be-954b-1b35aeba4bd0"
Template: "c2786e73-44c7-43be-954b-1b35aeba4bd0"
Path: /sitecore/templates/Project/Habitat Sites/Habitat Home/Pages/Landing Page/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180308T160021Z
