---
ID: "7fb5adeb-d50b-48e6-a7d1-f8fed281154f"
Parent: "72525431-8108-466d-ab8d-7ecd4149e884"
Template: "26fce9bf-0256-458d-8281-a713a5bf5520"
Path: /sitecore/content/Habitat SXA Sites/Sitecore Demo/Presentation/Cache Settings
DB: master
Created: 20190921T114747Z
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190921T114747Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "1575a960-c6e4-4de1-acb8-f22c92e38c81"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20190921T114747Z
