---
ID: "bce0701a-1e94-415e-95cf-5d9402cc2fd7"
Parent: "5bb199ed-f859-433f-8682-461303ad8faa"
Template: "1e5bfa08-0e32-4156-927e-930392fdcb92"
Path: /sitecore/content/Habitat Sites/Habitat Home Basic/Settings/Security Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "202eaae4-33b3-4db1-9170-4de88a27e7cd"
      Hint: User Profile
      Value: "{BCBF635A-9C02-4EFE-85FB-19358FAEAAB2}"
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171208T035457Z
    - ID: "81b370b0-9ea6-435d-be15-fcffb1cec57f"
      Hint: Register Page
      Value: 
    - ID: "927f708e-ab61-44ab-ab09-2a1a23e07e05"
      Hint: Forgot Password Page
      Value: "/sitecore/content/Habitat Sites/Habitat Home Basic/home/forgot-password"
    - ID: "a98f8b72-64aa-4a9c-90db-92f7aead55ad"
      Hint: Accounts Details Page
      Value: "/sitecore/content/Habitat Sites/Habitat Home Basic/home/account-management"
    - ID: "b8937bfd-64c0-4abe-8e64-b328ea3f1ea1"
      Hint: After Login Page
      Value: "/sitecore/content/Habitat Sites/Habitat Home Basic/home/account-management"
    - ID: "e90c6342-5bc9-4011-a3c5-eed1fca7eb7c"
      Hint: Login Page
      Value: /sitecore/content/Habitat Sites/Habitat Home Basic/home/login
    - ID: "f2f9cc39-fda5-4a19-82da-d03699d8f1be"
      Hint: Forgot Password Email Template
      Value: |
        <link text="" anchor="" linktype="internal" class="" title=""  querystring="" id="{2a106811-1c15-4196-8a5b-e4cf13740d0e}" />
    - ID: "f48206df-d2eb-4df2-9ac0-18a2e9c31f29"
      Hint: Register Outcome
      Value: "{52054874-4767-47DC-8099-8C08BFA307AA}"
- Language: "fr-CA"
  Fields:
  - ID: "41c6cc0e-389f-4d51-9990-fe35417b6666"
    Hint: __Preview
    Value: 
  - ID: "577f1689-7de4-4ad2-a15f-7fdc1759285f"
    Hint: __Long description
    Value: 
  - ID: "9541e67d-ce8c-4225-803d-33f7f29f09ef"
    Hint: __Short description
    Value: 
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: 
  Versions:
  - Version: 1
    Fields:
    - ID: "04bf00db-f5fb-41f7-8ab7-22408372a981"
      Hint: __Final Renderings
      Type: Layout
      Value: 
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: 
    - ID: "4c346442-e859-4efd-89b2-44aedf467d21"
      Hint: __Valid to
      Value: 
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "700f4aad-ad3b-4058-8673-a0cee765a1f7"
      Hint: __Content Test
      Value: 
    - ID: "7deb567c-87fa-48ce-9adc-8f35e05dde91"
      Hint: Interests Folder
      Value: 
    - ID: "81b370b0-9ea6-435d-be15-fcffb1cec57f"
      Hint: Register Page
      Value: /sitecore/content/Habitat Sites/Habitat Home/home/register
    - ID: "927f708e-ab61-44ab-ab09-2a1a23e07e05"
      Hint: Forgot Password Page
      Value: "/sitecore/content/Habitat Sites/Habitat Home/home/forgot-password"
    - ID: "a14f1b0c-4384-49ec-8790-28a440f3670c"
      Hint: __Semantics
      Type: Multilist with Search
      Value: 
    - ID: "a98f8b72-64aa-4a9c-90db-92f7aead55ad"
      Hint: Accounts Details Page
      Value: "/sitecore/content/Habitat Sites/Habitat Home/home/account-management"
    - ID: "b8937bfd-64c0-4abe-8e64-b328ea3f1ea1"
      Hint: After Login Page
      Value: "/sitecore/content/Habitat Sites/Habitat Home/home/account-management"
    - ID: "b8f42732-9cb8-478d-ae95-07e25345fb0f"
      Hint: __Hide version
      Type: checkbox
      Value: 0
    - ID: "c8f93afe-bfd4-4e8f-9c61-152559854661"
      Hint: __Valid from
      Value: 
    - ID: "ce693119-c97f-48fd-8154-27c4930ca7db"
      Hint: Title
      Value: 
    - ID: "e90c6342-5bc9-4011-a3c5-eed1fca7eb7c"
      Hint: Login Page
      Value: /sitecore/content/Habitat Sites/Habitat Home/home/login
    - ID: "f2f9cc39-fda5-4a19-82da-d03699d8f1be"
      Hint: Forgot Password Email Template
      Value: |
        <link text="" anchor="" linktype="internal" class="" title=""  querystring="" id="{5886C263-C45D-4CF8-8A28-9FF568BE6CAA}" />
- Language: "ja-JP"
  Versions:
  - Version: 1
    Fields:
    - ID: "202eaae4-33b3-4db1-9170-4de88a27e7cd"
      Hint: User Profile
      Value: "{BCBF635A-9C02-4EFE-85FB-19358FAEAAB2}"
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180321T104537Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "81b370b0-9ea6-435d-be15-fcffb1cec57f"
      Hint: Register Page
      Value: /sitecore/content/Habitat Sites/Habitat Home/home/register
    - ID: "927f708e-ab61-44ab-ab09-2a1a23e07e05"
      Hint: Forgot Password Page
      Value: "/sitecore/content/Habitat Sites/Habitat Home/home/forgot-password"
    - ID: "a98f8b72-64aa-4a9c-90db-92f7aead55ad"
      Hint: Accounts Details Page
      Value: "/sitecore/content/Habitat Sites/Habitat Home/home/account-management"
    - ID: "b8937bfd-64c0-4abe-8e64-b328ea3f1ea1"
      Hint: After Login Page
      Value: "/sitecore/content/Habitat Sites/Habitat Home/home/account-management"
    - ID: "e90c6342-5bc9-4011-a3c5-eed1fca7eb7c"
      Hint: Login Page
      Value: /sitecore/content/Habitat Sites/Habitat Home/home/login
    - ID: "f2f9cc39-fda5-4a19-82da-d03699d8f1be"
      Hint: Forgot Password Email Template
      Value: |
        <link text="" anchor="" linktype="internal" class="" title=""  querystring="" id="{5886C263-C45D-4CF8-8A28-9FF568BE6CAA}" />
    - ID: "f48206df-d2eb-4df2-9ac0-18a2e9c31f29"
      Hint: Register Outcome
      Value: "{52054874-4767-47DC-8099-8C08BFA307AA}"
