---
ID: "086d5f73-7e0a-444d-9ed1-42ba20c7d1b3"
Parent: "2bdf0532-c7a3-4d68-a802-17ce586c7cd7"
Template: "962b53c4-f93b-4df9-9821-415c867b8903"
Path: /sitecore/media library/Themes/Habitat Sites/Habitat Home Basic/gulp/serverConfig
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: "-/media/412E0A0BFE4243FE8F284BDE074230D1.ashx?h=16&thn=1&w=16"
- ID: "40e50ed9-ba07-4702-992e-a912738d32dc"
  Hint: Blob
  BlobID: "c8da850f-c7b1-4a6e-8d9b-70c5713c45ca"
  Value: eyAic2VydmVyT3B0aW9ucyI6IHsgInByb2plY3RQYXRoIjogIlxcVGhlbWVzIiwgInRoZW1lUGF0aCI6ICJcXEJhc2ljMiIgfSB9
- ID: "6954b7c7-2487-423f-8600-436cb3b6dc0e"
  Hint: Size
  Value: 75
- ID: "6f47a0a5-9c94-4b48-abeb-42d38def6054"
  Hint: Mime Type
  Value: "application/octet-stream"
- ID: "c06867fe-9a43-4c7d-b739-48780492d06f"
  Hint: Extension
  Value: json
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170707T125230Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
