---
ID: "20d0e3b0-28b6-40c9-840e-724e65e4755a"
Parent: "bc2be67b-632a-4368-bed6-5ff55d1251c2"
Template: "69dd5f28-429f-46b6-b55c-9da3500a7369"
Path: /sitecore/content/Habitat Sites/Habitat Home Basic/home/services
DB: master
SharedFields:
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: "{C6EBE5E6-BCE3-4BAB-A5F9-16382F8369FE}"
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 1225
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:p="p" xmlns:s="s"
      p:p="1">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
        <r
          uid="{DD41D365-2F17-4154-B933-09C6CFC57845}"
          p:before="*"
          s:cnd=""
          s:ds="{944488EB-297E-4B31-BDC0-9FB119D3366C}"
          s:id="{162AB463-0CE1-4295-8F7E-2E2E969984ED}"
          s:mvt=""
          s:par="GridParameters=%7B113BEF7C-97E6-46CA-8CF3-916F7FAA8DE2%7D&amp;FieldNames=%7BF04E97A8-F249-4674-B3E8-0BCE91B0B34F%7D&amp;Styles&amp;Reset Caching Options&amp;RenderingIdentifier&amp;DynamicPlaceholderId=8"
          s:ph="/main/sxa-content-container/container-1/container-5/column-2-6" />
        <r
          uid="{8B9DD353-F561-401D-9467-A9679CC4F2FA}"
          p:after="r[@uid='{DD41D365-2F17-4154-B933-09C6CFC57845}']"
          s:cnd=""
          s:ds="{8B549487-3BAB-4161-8FA8-2A0454CF71C7}"
          s:id="{162AB463-0CE1-4295-8F7E-2E2E969984ED}"
          s:mvt=""
          s:par="GridParameters=%7B113BEF7C-97E6-46CA-8CF3-916F7FAA8DE2%7D&amp;FieldNames=%7BF04E97A8-F249-4674-B3E8-0BCE91B0B34F%7D&amp;Styles&amp;Reset Caching Options&amp;RenderingIdentifier&amp;DynamicPlaceholderId=7"
          s:ph="/main/sxa-content-container/container-1/container-5/column-1-6" />
        <r
          uid="{84814DE4-BDAA-40C0-90C6-2DC5A5C0A53E}"
          p:after="r[@uid='{8B9DD353-F561-401D-9467-A9679CC4F2FA}']"
          s:id="{C25766C8-9AFD-4D28-87FE-147774F6806D}"
          s:par="SplitterSize=2&amp;EnabledPlaceholders=1%2C2&amp;Styles1&amp;Styles2&amp;Styles3&amp;Styles4&amp;Styles5&amp;Styles6&amp;Styles7&amp;Styles8&amp;ColumnWidth1=%7BFB140AEF-DE33-4088-9F1D-406C6BA32A8E%7D&amp;ColumnWidth2=%7BFB140AEF-DE33-4088-9F1D-406C6BA32A8E%7D&amp;ColumnWidth3&amp;ColumnWidth4&amp;ColumnWidth5&amp;ColumnWidth6&amp;ColumnWidth7&amp;ColumnWidth8&amp;Reset Caching Options&amp;DynamicPlaceholderId=6"
          s:ph="/main/sxa-content-container/container-1/container-5" />
        <r
          uid="{E8A9E49E-09A3-4D99-8376-8906EC526823}"
          p:after="r[@uid='{84814DE4-BDAA-40C0-90C6-2DC5A5C0A53E}']"
          s:cnd=""
          s:ds="local:/Data/Hero - Services"
          s:id="{6BCF8D8E-0A28-4844-BFB4-96C852BAD2DC}"
          s:mvt=""
          s:par="GridParameters=%7B113BEF7C-97E6-46CA-8CF3-916F7FAA8DE2%7D&amp;FieldNames=%7BD19D82CB-7A7E-4E3F-92FC-8ED3FD213260%7D&amp;Styles=%7B8F3DC40A-9195-4818-AAEB-9C4F529EAFD4%7D&amp;Reset Caching Options&amp;RenderingIdentifier&amp;DynamicPlaceholderId=1"
          s:ph="/main/sxa-content-container/container-1" />
        <r
          uid="{98D04520-E485-4FAF-B1E2-5FC86D0A89E8}"
          p:after="r[@uid='{E8A9E49E-09A3-4D99-8376-8906EC526823}']"
          s:cnd=""
          s:ds="local:/Data/Promo - Gift Card"
          s:id="{51C13F03-8364-4F61-B860-2EC6CA7439B3}"
          s:mvt=""
          s:par="GridParameters=%7B113BEF7C-97E6-46CA-8CF3-916F7FAA8DE2%7D&amp;FieldNames=%7B184DC7A4-FDBB-446F-94BE-30B44B12C2AD%7D&amp;Styles&amp;Reset Caching Options&amp;RenderingIdentifier&amp;DynamicPlaceholderId=2"
          s:ph="/main/sxa-content-container/container-1" />
        <r
          uid="{E6F7EDEB-9037-4622-884B-295F86CD56B3}"
          p:after="r[@uid='{98D04520-E485-4FAF-B1E2-5FC86D0A89E8}']"
          s:cnd=""
          s:ds="local:/Data/Promo - Home Installation"
          s:id="{51C13F03-8364-4F61-B860-2EC6CA7439B3}"
          s:mvt=""
          s:par="GridParameters=%7B113BEF7C-97E6-46CA-8CF3-916F7FAA8DE2%7D&amp;FieldNames=%7BF8C8F184-053D-4947-840B-A96495DB434C%7D&amp;Styles&amp;Reset Caching Options&amp;RenderingIdentifier&amp;DynamicPlaceholderId=3"
          s:ph="/main/sxa-content-container/container-1" />
        <r
          uid="{702AFD09-FF48-4EED-8675-A871123718E9}"
          p:after="r[@uid='{E6F7EDEB-9037-4622-884B-295F86CD56B3}']"
          s:cnd=""
          s:ds="local:/Data/Promo - Ultimate Smart Home Checklist"
          s:id="{51C13F03-8364-4F61-B860-2EC6CA7439B3}"
          s:mvt=""
          s:par="GridParameters=%7B113BEF7C-97E6-46CA-8CF3-916F7FAA8DE2%7D&amp;FieldNames=%7B184DC7A4-FDBB-446F-94BE-30B44B12C2AD%7D&amp;Styles&amp;Reset Caching Options&amp;RenderingIdentifier&amp;DynamicPlaceholderId=4"
          s:ph="/main/sxa-content-container/container-1" />
        <r
          uid="{C85CCAEE-554B-48F3-BC89-EBE865AC7B2F}"
          p:after="*[1=2]"
          s:cnd=""
          s:ds=""
          s:id="{896A2C68-1362-4E88-8BA0-1805AE6D4837}"
          s:mvt=""
          s:par="GridParameters=%7B113BEF7C-97E6-46CA-8CF3-916F7FAA8DE2%7D&amp;BackgroundImage&amp;Styles=%7B8F3DC40A-9195-4818-AAEB-9C4F529EAFD4%7D%7C%7BA58D59AB-FBE6-4EB6-8465-EC68D11C4D2A%7D&amp;Reset Caching Options&amp;RenderingIdentifier&amp;DynamicPlaceholderId=5"
          s:ph="/main/sxa-content-container/container-1" />
      </d>
    </r>
Languages:
- Language: en
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Services
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180920T204730Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{E93E190F-3398-489D-B3A3-A3B0D9BB33C5}"
    - ID: "4e0720e9-9d50-4ddc-87cf-ecd65e8e94c8"
      Hint: NavigationTitle
      Value: Services
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "e2a634fd-5177-46de-b629-5393caed77d7"
      Hint: Title
      Value: Services
- Language: "fr-CA"
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Services
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180920T204730Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{E93E190F-3398-489D-B3A3-A3B0D9BB33C5}"
    - ID: "4e0720e9-9d50-4ddc-87cf-ecd65e8e94c8"
      Hint: NavigationTitle
      Value: Services
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "e2a634fd-5177-46de-b629-5393caed77d7"
      Hint: Title
      Value: Services
- Language: "ja-JP"
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Services
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181025T015520Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{FF509B64-B6D4-4FB7-9718-C4218B992740}"
    - ID: "4e0720e9-9d50-4ddc-87cf-ecd65e8e94c8"
      Hint: NavigationTitle
      Value: Services
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "e2a634fd-5177-46de-b629-5393caed77d7"
      Hint: Title
      Value: Services
