---
ID: "1e5bfa08-0e32-4156-927e-930392fdcb92"
Parent: "343c59cd-c701-407d-b3ae-b56e0071c40f"
Template: "ab86861a-6030-46c5-b394-e8f99e8b87db"
Path: /sitecore/templates/Feature/Habitat Home/Accounts/Security Settings
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: Office/32x32/webcam.png
- ID: "12c33f3f-86c5-43a5-aeb4-5598cec45116"
  Hint: __Base template
  Type: tree list
  Value: |
    {4C7D90D2-CEAA-4A1F-8302-63D831E8E7B6}
    {CB2C27F8-01F4-48FF-82F5-5256F8B1FDC3}
    {7E5DE17D-5975-40B7-952E-45E646699318}
- ID: "f7d48a55-2158-4f02-9356-756654404f73"
  Hint: __Standard values
  Value: "{4876A0E8-3F79-4B93-BC23-61E7FC5DFCC5}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171206T134935Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
