---
ID: "fb17d90d-dd19-4b58-947e-ef8c6a7a48ca"
Parent: "cc9b9eef-1345-4db4-8a36-a002ec113419"
Template: "cc9b9eef-1345-4db4-8a36-a002ec113419"
Path: /sitecore/templates/Project/Demo Shared SXA Sites/Global/Pages/Resource Pages/Whitepaper Resource/__Standard Values
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: office/32x32/document_cup.png
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "2237f784-23d5-4bfa-b766-977ef7344f0b"
      Hint: ResourceType
      Value: Whitepaper
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210107T150409Z
