---
ID: "1de591d7-f95b-403e-a800-629d072dd75c"
Parent: "9b87d09a-3a73-4e0a-8ee8-c192719d256f"
Template: "9b87d09a-3a73-4e0a-8ee8-c192719d256f"
Path: /sitecore/templates/Project/Habitat SXA Sites/Habitat Home/Pages/Event Page/__Standard Values
DB: master
Created: 20191014T150330Z
SharedFields:
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{BCFC7537-EFF4-434C-96F5-BF4F55FD175B}">
        <r
          ds=""
          id="{BFC5FDAA-232B-4186-BB11-FA42866C18F7}"
          par="GridParameters&amp;FieldNames=%7BAB37B61D-B9A9-47B0-B964-8B85B533EEDC%7D&amp;Styles&amp;Reset Caching Options&amp;RenderingIdentifier&amp;DynamicPlaceholderId=1"
          ph="/main/sxa-content-container/container-1"
          uid="{4DD99867-B905-43D2-BAA9-9125264D6378}" />
      </d>
      <d
        id="{0B4A31C9-712D-4578-A396-2DDC0F34B63A}"
        l="{72C595AD-68BB-44BC-B5CD-2A857039515F}" />
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20191014T150330Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "85fd0eb4-0330-4c65-b9a5-d2c1f94e1bed"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20191014T150858Z
