---
ID: "ebd498ba-a204-41e3-953d-94ced6cf775f"
Parent: "8dcecf0c-80bf-4a34-af29-45f5f1463399"
Template: "1a7d9344-df9d-4605-99d8-4d752a9edb2f"
Path: /sitecore/content/Habitat Standard Sites/Habitat Home Corporate/Settings
DB: master
SharedFields:
- ID: "6d85d254-3f84-4a22-9d29-61832b08df2d"
  Hint: Logo
  Value: |
    <image mediaid="{90D766AA-C55E-4393-94ED-63854FD8C30A}" />
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190104T132841Z
    - ID: "73f9f836-ecc6-47a8-818b-125036bc5b12"
      Hint: Favicon
      Value: |
        <image mediaid="{0BF91DD4-1A53-4A4A-AFA3-4F310D7E9C0E}" />
    - ID: "9cb71d9c-0785-4f9b-95cd-74c3becf9da2"
      Hint: Title
      Value: Habitat Corporate
- Language: "ja-JP"
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: 設定
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190409T150045Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "9cb71d9c-0785-4f9b-95cd-74c3becf9da2"
      Hint: Title
      Value: Habitat コーポレート
