---
ID: "fa458bcd-a00b-487d-9f3e-be0f18466b54"
Parent: "2b234fe0-e78c-4023-8a1a-1025922d545f"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/Feature/Habitat Home/Search/SearchConfigurationSettings/Search Configuration Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190507T081232Z
