---
ID: "62907b2b-9c0a-4a2a-9758-7b29b22ed91b"
Parent: "3a1e055a-9933-4f01-bfb1-e123f221d0cb"
Template: "3a1e055a-9933-4f01-bfb1-e123f221d0cb"
Path: /sitecore/templates/Feature/Habitat Home/Components/NavigationBase/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "03f0061a-309d-4732-a722-2f2a1488ac60"
      Hint: NavigationTitle
      Value: $name
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190423T105303Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
