---
ID: "fff47e80-0311-4c65-94d5-bbb8a15dcf39"
Parent: "4ad7eb6b-d0f6-479d-a00f-0aa1bf984a79"
Template: "4ad7eb6b-d0f6-479d-a00f-0aa1bf984a79"
Path: /sitecore/templates/Project/Habitat Sites/Partial Designs/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: |
    {D623F3AD-2202-473C-998B-798B5302ADE2}
    {EAFFC9F9-3684-4650-92F4-78560BED789B}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171027T151047Z
