---
ID: "a1ea5c1a-ed8f-4280-b9df-23c03905bb50"
Parent: "be2a1204-f7ba-4be3-933d-190c97496700"
Template: "be2a1204-f7ba-4be3-933d-190c97496700"
Path: /sitecore/templates/Project/Habitat SXA Sites/Global/Settings/__Standard Values
DB: master
SharedFields:
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171027T151055Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\virtualssuser
