---
ID: "8a711cbf-562b-4e67-b57b-2772d7b17453"
Parent: "2fc78d5d-ae45-46e2-bb7e-7f6d343fd181"
Template: "2fc78d5d-ae45-46e2-bb7e-7f6d343fd181"
Path: /sitecore/templates/Feature/Habitat Home/Media/Video/__Standard Values
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: /~/icon/multimedia/32x32/new_video.png
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190424T124829Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
