---
ID: "185654c1-ce0a-4fa7-8ab5-766f384c306d"
Parent: "36ac0b4c-c464-460b-bdba-2d2f252073bb"
Template: "36ac0b4c-c464-460b-bdba-2d2f252073bb"
Path: /sitecore/templates/Project/Habitat SXA Sites/Global/Tenant/__Standard Values
DB: master
SharedFields:
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171027T151045Z
