---
ID: "79c4342d-0434-4007-a700-5c634dbc8c88"
Parent: "c2973326-c35a-43a3-a380-3c4ca7edf18d"
Template: "962b53c4-f93b-4df9-9821-415c867b8903"
Path: /sitecore/media library/Themes/Habitat SXA Sites/Habitat Home Espresso/gulp/tasks/gulpUploading
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: "-/media/0684008FA6F84CBBAA99322647B34738.ashx?h=16&thn=1&w=16"
- ID: "40e50ed9-ba07-4702-992e-a912738d32dc"
  Hint: Blob
  BlobID: "48f6b12e-dcef-477a-8dd8-c1956f77cd71"
  Value: aW1wb3J0IGd1bHAgZnJvbSAnZ3VscCc7DQppbXBvcnQgc2FzcyBmcm9tICdndWxwLXNhc3MnOw0KaW1wb3J0IHdhdGNoIGZyb20gJ2d1bHAtd2F0Y2gnOw0KLy8NCmltcG9ydCBsb2dpbiBmcm9tICcuL2xvZ2luJzsNCmltcG9ydCBjb25maWcgZnJvbSAnLi4vY29uZmlnJzsNCmltcG9ydCBmaWxlQWN0aW9uUmVzb2x2ZXIgZnJvbSAnLi4vdXRpbC9maWxlQWN0aW9uUmVzb2x2ZXInOw0KLy8NCg0KZ3VscC50YXNrKCd1cGxvYWQtZ3VscCcsIFsnbG9naW4nXSwgKCkgPT4gew0KICAgIHJldHVybiBndWxwLnNyYygnZ3VscC8qKi8qLmpzJykNCiAgICAgICAgLnBpcGUoZ3VscC5kZXN0KGZ1bmN0aW9uKGZpbGUpIHsNCiAgICAgICAgICAgIGZpbGVBY3Rpb25SZXNvbHZlcihmaWxlLCB0cnVlKTsNCiAgICAgICAgICAgIHJldHVybiAnLi8nOw0KICAgICAgICB9KSkNCn0pOw0KZ3VscC50YXNrKCd3YXRjaC1ndWxwJywgWydsb2dpbiddLCAoKSA9PiB7DQogICAgcmV0dXJuIHdhdGNoKFsnZ3VscC8qKi8qLmpzJywgJ2d1bHAvKiovKi5qc29uJ10sIGZ1bmN0aW9uKGZpbGUpIHsNCiAgICAgICAgZmlsZUFjdGlvblJlc29sdmVyKGZpbGUpOw0KICAgIH0pDQp9KTs=
- ID: "6954b7c7-2487-423f-8600-436cb3b6dc0e"
  Hint: Size
  Value: 599
- ID: "6f47a0a5-9c94-4b48-abeb-42d38def6054"
  Hint: Mime Type
  Value: "application/x-javascript"
- ID: "c06867fe-9a43-4c7d-b739-48780492d06f"
  Hint: Extension
  Value: js
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181120T042720Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
