---
ID: "5147db7b-dd5d-4b5e-b1e5-e75a8b73399e"
Parent: "ebd498ba-a204-41e3-953d-94ced6cf775f"
Template: "9b479b57-aae9-4601-abb4-e48adc72b368"
Path: /sitecore/content/Habitat Standard Sites/Habitat Home Corporate/Settings/News Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "1c3cd945-0297-4609-9d65-ee26b74d4a4e"
      Hint: NewsOverviewDefaultNumberOfItems
      Value: 10
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190502T052015Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "88c6f83c-41f7-46a2-801c-09d136bf562a"
      Hint: NewsSlugNotFoundPage
      Value: "{286665EC-AEB3-4CDD-9C1A-8FDD1BA80CF4}"
    - ID: "c6b8eb78-8193-4728-b1d6-5a9185463af1"
      Hint: NewsWildcardItem
      Value: "{3384C17B-C75B-4C41-826A-013DA05D446C}"
