---
ID: "3186a30a-ab21-45b6-872a-c8893987fec4"
Parent: "14592221-27d2-4d4b-80ea-1a15effe021c"
Template: "14592221-27d2-4d4b-80ea-1a15effe021c"
Path: /sitecore/templates/Project/Demo Shared SXA Sites/SitecoreDemo/Fins/Content Hub Entity Types/Content Hub Blog/__Standard Values
DB: master
SharedFields:
- ID: "c9283d9e-7c29-4419-9c28-5a5c8ff53e84"
  Hint: __Bucketable
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190614T161122Z
