---
ID: "283d318e-c2e7-41cf-a74b-c3f3daefe312"
Parent: "4415e38e-b7c3-48ec-9070-dca80de71158"
Template: "962b53c4-f93b-4df9-9821-415c867b8903"
Path: /sitecore/media library/Themes/Habitat Sites/Habitat Home Raspberry/gulp/tasks/watchSassSource
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: "-/media/283D318EC2E741CFA74BC3F3DAEFE312.ashx?h=16&thn=1&w=16"
- ID: "40e50ed9-ba07-4702-992e-a912738d32dc"
  Hint: Blob
  BlobID: "1cae74ec-b6c4-4529-bc1e-3bc8ba61b534"
  Value: aW1wb3J0IGd1bHAgZnJvbSAnZ3VscCc7DQppbXBvcnQgc2FzcyBmcm9tICdndWxwLXNhc3MnOw0KaW1wb3J0IHdhdGNoIGZyb20gJ2d1bHAtd2F0Y2gnOw0KLy8NCmltcG9ydCBsb2dpbiBmcm9tICcuL2xvZ2luJzsNCmltcG9ydCBjb25maWcgZnJvbSAnLi4vY29uZmlnJzsNCmltcG9ydCBmaWxlQWN0aW9uUmVzb2x2ZXIgZnJvbSAnLi4vdXRpbC9maWxlQWN0aW9uUmVzb2x2ZXInOw0KDQpndWxwLnRhc2soJ3dhdGNoLXNvdXJjZS1zYXNzJywgWydsb2dpbiddLCAoKSA9PiB7DQogICAgdmFyIGNvbmYgPSBjb25maWcuc2FzczsNCiAgICByZXR1cm4gd2F0Y2goY29uZi5yb290LCBmdW5jdGlvbihmaWxlKSB7DQogICAgICAgIGZpbGVBY3Rpb25SZXNvbHZlcihmaWxlKTsNCiAgICB9KQ0KfSk7DQoNCmd1bHAudGFzaygnc2Fzcy1zb3VyY2Utd2F0Y2gnLCBbJ2xvZ2luJ10sDQogICAgZnVuY3Rpb24oKSB7DQogICAgICAgIGdsb2JhbC5pc1dhdGNoaW5nID0gdHJ1ZTsNCiAgICAgICAgZ3VscC5ydW4oJ3dhdGNoLXNvdXJjZS1zYXNzJykNCiAgICB9KQ==
- ID: "6954b7c7-2487-423f-8600-436cb3b6dc0e"
  Hint: Size
  Value: 538
- ID: "6f47a0a5-9c94-4b48-abeb-42d38def6054"
  Hint: Mime Type
  Value: "application/x-javascript"
- ID: "c06867fe-9a43-4c7d-b739-48780492d06f"
  Hint: Extension
  Value: js
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180223T050235Z
