---
ID: "0487432e-76b3-40a6-ae7f-1e539557df67"
Parent: "3a7a131c-23e2-4614-9b69-fab668499a59"
Template: "3a7a131c-23e2-4614-9b69-fab668499a59"
Path: /sitecore/templates/Feature/Habitat Sites/Page Content/Rendering Parameters/Page Teaser/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180307T042139Z
