---
ID: "3312200a-4c64-4398-81db-7f52af209421"
Parent: "e9937f22-dbca-436c-a37e-efe6915759ae"
Template: "e9937f22-dbca-436c-a37e-efe6915759ae"
Path: /sitecore/templates/Feature/Habitat Home/Components/Component Folder/__Standard Values
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: Office/32x32/folders.png
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: |
    {9BCD885B-8B18-4EA5-AEA1-BC5F918D5B90}
    {E9937F22-DBCA-436C-A37E-EFE6915759AE}
    {2D77E72E-4CEE-47FA-97C1-D29C508A4173}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181226T142634Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
