---
ID: "0ef4eaa6-e447-49ca-a382-50fb4da40c3d"
Parent: "aa74d134-b916-47b2-b40a-2c5b906a2cb0"
Template: "5996ae17-2739-49f0-a1c8-c5edbe3f0025"
Path: /sitecore/content/Habitat Sites/Habitat Home/Data/Forms/Form Actions Settings/Content Finder/Interest Question Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171215T050435Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8c512534-ba02-49fc-91be-66da6e6aa1b6"
      Hint: Form Question
      Value: "{5C6D0D54-A8EC-41D1-A5C0-518FE375197C}"
- Language: "fr-CA"
  Fields:
  - ID: "41c6cc0e-389f-4d51-9990-fe35417b6666"
    Hint: __Preview
    Value: 
  - ID: "577f1689-7de4-4ad2-a15f-7fdc1759285f"
    Hint: __Long description
    Value: 
  - ID: "9541e67d-ce8c-4225-803d-33f7f29f09ef"
    Hint: __Short description
    Value: 
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: 
  Versions:
  - Version: 1
    Fields:
    - ID: "04bf00db-f5fb-41f7-8ab7-22408372a981"
      Hint: __Final Renderings
      Type: Layout
      Value: 
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171215T050435Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: 
    - ID: "4c346442-e859-4efd-89b2-44aedf467d21"
      Hint: __Valid to
      Value: 
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "700f4aad-ad3b-4058-8673-a0cee765a1f7"
      Hint: __Content Test
      Value: 
    - ID: "8c512534-ba02-49fc-91be-66da6e6aa1b6"
      Hint: Form Question
      Value: "{5C6D0D54-A8EC-41D1-A5C0-518FE375197C}"
    - ID: "a14f1b0c-4384-49ec-8790-28a440f3670c"
      Hint: __Semantics
      Type: Multilist with Search
      Value: 
    - ID: "b8f42732-9cb8-478d-ae95-07e25345fb0f"
      Hint: __Hide version
      Type: checkbox
      Value: 0
    - ID: "c8f93afe-bfd4-4e8f-9c61-152559854661"
      Hint: __Valid from
      Value: 
- Language: "ja-JP"
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: 興味のある質問設定
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180321T104506Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8c512534-ba02-49fc-91be-66da6e6aa1b6"
      Hint: Form Question
      Value: "{5C6D0D54-A8EC-41D1-A5C0-518FE375197C}"
