---
ID: "57745e81-b2f1-4c54-84ee-ca488fb41a3d"
Parent: "f84f4dde-30d1-4ce5-b51c-c58d0ad1fa12"
Template: "962b53c4-f93b-4df9-9821-415c867b8903"
Path: /sitecore/media library/Themes/Habitat SXA Sites/Habitat Home v2/gulp/tasks/sassComponents
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: "-/media/57745E81B2F14C5484EECA488FB41A3D.ashx?h=16&thn=1&w=16"
- ID: "40e50ed9-ba07-4702-992e-a912738d32dc"
  Hint: Blob
  BlobID: "74c95b35-b040-4675-b7dd-4c38f5b8eb87"
  Value: aW1wb3J0IGd1bHAgZnJvbSAiZ3VscCI7DQovLw0KaW1wb3J0IGNvbXBvbmVudHNCdWlsZGVyIGZyb20gJy4uL3V0aWwvc2Fzc0NvbXBvbmVudHNCdWlsZGVyJzsNCg0KZ3VscC50YXNrKCdzYXNzQ29tcG9uZW50cycsIFsnbG9naW4nXSwgKCkgPT4gew0KICAgIHJldHVybiBjb21wb25lbnRzQnVpbGRlcigpDQp9KTs=
- ID: "6954b7c7-2487-423f-8600-436cb3b6dc0e"
  Hint: Size
  Value: 179
- ID: "6f47a0a5-9c94-4b48-abeb-42d38def6054"
  Hint: Mime Type
  Value: "application/x-javascript"
- ID: "c06867fe-9a43-4c7d-b739-48780492d06f"
  Hint: Extension
  Value: js
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181120T042720Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
