---
ID: "83acec67-ca49-485d-ae35-d1dde3636638"
Parent: "67a3063b-3801-4c53-8762-acfa1cd75113"
Template: "67a3063b-3801-4c53-8762-acfa1cd75113"
Path: /sitecore/templates/Project/Habitat SXA Sites/Global/Pages/Login Page/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171211T103300Z
