---
ID: "11b5340d-b993-4028-83c0-054a86df5eb8"
Parent: "3dc769cd-d471-4187-927f-5a60a520edb1"
Template: "3dc769cd-d471-4187-927f-5a60a520edb1"
Path: /sitecore/templates/Feature/Habitat Home/Search/SearchBase/__Standard Values
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: /~/icon/apps/32x32/Search.png
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190509T081744Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
