---
ID: "02bb6020-825f-4d85-94be-b7ace6ce3572"
Parent: "643a85f5-c9f1-4836-b17b-35ade22d03d3"
Template: "643a85f5-c9f1-4836-b17b-35ade22d03d3"
Path: /sitecore/templates/Feature/Habitat Sites/Page Content/Hero/__Standard Values
DB: master
SharedFields:
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180322T014307Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
