---
ID: "5e5dc9a6-8385-44e9-8096-396cbde9ea7d"
Parent: "d623f3ad-2202-473c-998b-798b5302ade2"
Template: "d623f3ad-2202-473c-998b-798b5302ade2"
Path: /sitecore/templates/Project/Habitat SXA Sites/Global/Partial Design Folder/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: |
    {D623F3AD-2202-473C-998B-798B5302ADE2}
    {EAFFC9F9-3684-4650-92F4-78560BED789B}
    {9F54E3D8-1BBA-4442-84E1-F0528B780ECC}
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171027T151054Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\virtualssuser
