---
ID: "499685c5-7adf-4731-9fe9-81f832949134"
Parent: "e3b950bb-1b55-4cdd-819f-031b3be1a66c"
Template: "e3b950bb-1b55-4cdd-819f-031b3be1a66c"
Path: /sitecore/templates/Project/Habitat SXA Sites/Global/Pages/L2 Content Page/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171117T212543Z
