---
ID: "6e325452-cc21-4ab0-b705-67e50b02f325"
Parent: "4fded342-b304-42f7-8091-ae3eb660ba4c"
Template: "4fded342-b304-42f7-8091-ae3eb660ba4c"
Path: /sitecore/templates/Feature/Habitat Home/Forms/PatternCardActionMapping/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171215T170433Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "ecb328c3-8f41-4c0b-8fdf-a01096146f3b"
      Hint: Mapped Value
      Value: $name
