---
ID: "5d067d5a-76bb-4faf-9ffe-5458caaf4a11"
Parent: "26745e9d-be97-4902-993d-1982b47b64bf"
Template: "26745e9d-be97-4902-993d-1982b47b64bf"
Path: /sitecore/templates/Project/Demo Shared SXA Sites/SitecoreDemo/Fins/Verticals/Fins/Fin L1 Content Page/__Standard Values
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: Apps/32x32/Invoices.png
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: |
    {459A510B-5E2C-425F-A321-1D9423937EB0}
    {46404C72-8886-4DA3-AF43-F2D124614D0F}
    {60C2F379-9FFD-4AA6-9D6D-87494ACEEDDD}
    {BD74A392-DACD-4C23-853A-D520762B33A1}
    {C14B6289-8AC2-439C-9E5B-40DE9F820C3F}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171117T175503Z
