---
ID: "595d4a23-509e-483b-a174-e8f842a692cb"
Parent: "64474624-5671-422f-ae0d-1b85168cb2a9"
Template: "68b0cf3c-9150-4db7-acab-f626e59bca6d"
Path: /sitecore/system/Marketing Control Panel/Taxonomies/Campaign facet 1/Content Focus/Automation
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180628T171754Z
- Language: "ja-JP"
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: ????????
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190125T061634Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
