---
ID: "5bb199ed-f859-433f-8682-461303ad8faa"
Parent: "d2b97f33-2af4-42a9-a1d4-08f4e2a22c87"
Template: "be2a1204-f7ba-4be3-933d-190c97496700"
Path: /sitecore/content/Habitat Sites/Habitat Home Basic/Settings
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: |
    {11F57D7B-CBB2-4647-B98C-71457564BA4F}
    {0D792404-79AA-483D-BB0C-50785F2E295B}
    {F86FE270-00A4-492F-BFAF-5BF27E40CE13}
    {E1CF805E-7F49-4EC9-A25A-182DC798CB5F}
    {DC66D5DA-3216-48E6-AE78-BAC8445B6A46}
    {70461699-48E4-45FA-B74B-0CCE849FCA6A}
    {20EF5E69-B366-4E9E-960B-E451B24DBD46}
    {5C76AD53-96CD-4B96-9690-DD9AF2650171}
    {44936C95-BCA9-4FB3-9D98-2066A5FBBB4D}
    {5A6BF1D1-836B-425A-A6E6-32CEAA8FF3A5}
    {B14BAB5B-8965-466B-886B-1F93175BCAB3}
    {041C1F9F-99A4-4EE6-8308-985499F91032}
- ID: "332a4c4e-222d-4a94-abcc-79f92f3b7b4b"
  Hint: DatasourceBehaviour
  Value: PromptForNameStoreUnderPage
- ID: "ad84cc6b-32ef-49d8-9326-916976cb2520"
  Hint: Grid Mapping
  Value: "%7bFE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3%7d%3d%257B8250F168-8C71-49AF-A4C2-F2C95D607CB8%257D"
- ID: "af332c24-fe17-41e7-8caf-8e64c588fe72"
  Hint: EditingTheme
  Value: 
- ID: "beeede03-ab13-4558-96f9-c3e8957b46f8"
  Hint: Themes
  Type: Treelist
  Value: |
    {3F46272C-F3B8-4913-8C00-3816B436A4D3}
    {FBE5E6A7-EEEE-4151-B8F1-02BCFDC9EBFA}
    {FE579EA5-4FF1-47D4-A514-6EA5EEE9AB01}
    {24A18569-AC94-4C12-8BC1-97E6A1319C01}
- ID: "e81e1f9e-8b87-495b-9cb7-84a2a23133be"
  Hint: MediaLibrary
  Value: "{5E327CA2-858A-45A5-BC38-39076781C1A0}"
- ID: "e8881464-38af-4655-be4a-ee10586578a2"
  Hint: Templates
  Value: "{93F3857B-50B9-4A2D-ADE8-95F3B2F53005}"
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{3E739E69-859C-4694-8D14-2BA6CA779CC6}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "202eaae4-33b3-4db1-9170-4de88a27e7cd"
      Hint: User Profile
      Value: "{BCBF635A-9C02-4EFE-85FB-19358FAEAAB2}"
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171027T190505Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\virtualssuser
- Language: "fr-CA"
  Fields:
  - ID: "41c6cc0e-389f-4d51-9990-fe35417b6666"
    Hint: __Preview
    Value: 
  - ID: "577f1689-7de4-4ad2-a15f-7fdc1759285f"
    Hint: __Long description
    Value: 
  - ID: "9541e67d-ce8c-4225-803d-33f7f29f09ef"
    Hint: __Short description
    Value: 
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: 
  Versions:
  - Version: 1
    Fields:
    - ID: "04bf00db-f5fb-41f7-8ab7-22408372a981"
      Hint: __Final Renderings
      Type: Layout
      Value: 
    - ID: "202eaae4-33b3-4db1-9170-4de88a27e7cd"
      Hint: User Profile
      Value: "{BCBF635A-9C02-4EFE-85FB-19358FAEAAB2}"
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171027T190505Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: 
    - ID: "4b5d1cb7-e617-4cd0-a7e8-cc8a9fd80688"
      Hint: Rule
      Type: Rules
      Value: 
    - ID: "4c346442-e859-4efd-89b2-44aedf467d21"
      Hint: __Valid to
      Value: 
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\virtualssuser
    - ID: "700f4aad-ad3b-4058-8673-a0cee765a1f7"
      Hint: __Content Test
      Value: 
    - ID: "7deb567c-87fa-48ce-9adc-8f35e05dde91"
      Hint: Interests Folder
      Value: 
    - ID: "a14f1b0c-4384-49ec-8790-28a440f3670c"
      Hint: __Semantics
      Type: Multilist with Search
      Value: 
    - ID: "b8f42732-9cb8-478d-ae95-07e25345fb0f"
      Hint: __Hide version
      Type: checkbox
      Value: 0
    - ID: "c8f93afe-bfd4-4e8f-9c61-152559854661"
      Hint: __Valid from
      Value: 
    - ID: "ce693119-c97f-48fd-8154-27c4930ca7db"
      Hint: Title
      Value: 
- Language: "ja-JP"
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: 設定
  Versions:
  - Version: 1
    Fields:
    - ID: "202eaae4-33b3-4db1-9170-4de88a27e7cd"
      Hint: User Profile
      Value: "{BCBF635A-9C02-4EFE-85FB-19358FAEAAB2}"
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180321T104536Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
