---
ID: "17f2625d-948f-4708-b83d-35241c80a6a5"
Parent: "5092bf42-1fa9-4676-8d1e-475c7f6f8575"
Template: "962b53c4-f93b-4df9-9821-415c867b8903"
Path: /sitecore/media library/Themes/Habitat SXA Sites/Habitat Home Raspberry/gulp/tasks/watchCss
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: "-/media/C3832376399946C38D970463999F757E.ashx?h=16&thn=1&w=16"
- ID: "40e50ed9-ba07-4702-992e-a912738d32dc"
  Hint: Blob
  BlobID: "201cc5df-5e78-437b-9aca-adeac355cf6e"
  Value: aW1wb3J0IGd1bHAgZnJvbSAnZ3VscCc7DQppbXBvcnQgc2FzcyBmcm9tICdndWxwLXNhc3MnOw0KaW1wb3J0IHdhdGNoIGZyb20gJ2d1bHAtd2F0Y2gnOw0KaW1wb3J0IGNvbG9ycyBmcm9tICdjb2xvcnMnDQovLw0KaW1wb3J0IGxvZ2luIGZyb20gJy4vbG9naW4nOw0KaW1wb3J0IGNvbmZpZyBmcm9tICcuLi9jb25maWcnOw0KaW1wb3J0IGZpbGVBY3Rpb25SZXNvbHZlciBmcm9tICcuLi91dGlsL2ZpbGVBY3Rpb25SZXNvbHZlcic7DQovLw0KDQpndWxwLnRhc2soJ3dhdGNoLWNzcycsIFsnbG9naW4nXSwgKCkgPT4gew0KICAgIHZhciBjb25mID0gY29uZmlnLmNzczsNCiAgICBzZXRUaW1lb3V0KGZ1bmN0aW9uKCkgew0KICAgICAgICBjb25zb2xlLmxvZygnV2F0Y2hpbmcgQ1NTIGZpbGVzIHN0YXJ0ZWQuLi4nLmdyZWVuKTsNCiAgICB9LCAwKTsNCiAgICByZXR1cm4gd2F0Y2goY29uZi5wYXRoLCBmdW5jdGlvbihmaWxlKSB7DQogICAgICAgIGZpbGVBY3Rpb25SZXNvbHZlcihmaWxlKTsNCiAgICB9KQ0KfSk7DQoNCmd1bHAudGFzaygnY3NzLXdhdGNoJywgWydsb2dpbiddLA0KICAgIGZ1bmN0aW9uKCkgew0KICAgICAgICBnbG9iYWwuaXNXYXRjaGluZyA9IHRydWU7DQogICAgICAgIGd1bHAucnVuKCd3YXRjaC1jc3MnKQ0KICAgIH0p
- ID: "6954b7c7-2487-423f-8600-436cb3b6dc0e"
  Hint: Size
  Value: 648
- ID: "6f47a0a5-9c94-4b48-abeb-42d38def6054"
  Hint: Mime Type
  Value: "application/x-javascript"
- ID: "c06867fe-9a43-4c7d-b739-48780492d06f"
  Hint: Extension
  Value: js
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181120T042722Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
